owner: redwipe
repo: upptime

sites:
  - name: Marketing Site
    url: https://redwipe.com
  - name: Dashboard
    url: https://app.redwipe.com
  - name: API
    url: https://api.redwipe.com/healthz
  - name: Docs
    url: https://docs.redwipe.com

status-website:
  cname: status.redwipe.com
  name: Redwipe Status
  theme: dark
